[package]
name = "suite"
version = "0.1.0"
authors = ["Alexander Slesarev <alex.slesarev@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.9"
regex = "1.3.1"
itertools = "0.8.1"
clap = "2.33.0"
plotters = { git = "https://github.com/nuald/plotters", branch = "boxplot" }
