[package]
name = "simple-web-server"
version = "0.0.2"
authors = ["Alexander Slesarev <alex.slesarev@gmail.com>"]

[dependencies]
regex = "1.1.9"
lazy_static = "1.3.0"
hyper = "0.12.33"
libc = "0.2.60"
