[package]
name = "simple-web-server"
version = "0.0.2"
authors = ["Alexander Slesarev <alex.slesarev@gmail.com>"]

[dependencies]
regex = "1.3.1"
lazy_static = "1.4.0"
hyper = "0.12.35"
libc = "0.2.65"
