[package]
name = "simple-web-server"
version = "0.0.1"
authors = ["Alexander Slesarev <alex.slesarev@gmail.com>"]

[dependencies]
regex = "0.2.5"
lazy_static = "1.0.0"
futures = "0.1.18"
hyper = "0.11.15"
libc = "0.2.36"
